version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - 'path.repo=/var/backups/elastic'
      - 'path.logs=/var/kat/app'
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "8200:9200"
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./var/backups/elastic:/var/backups/elastic
      - ./var/kat/app:/var/kat/app
      - ./log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - LOGGING_QUIET=true
      - SERVER_PUBLICBASEURL=http://localhost:6601
    ports:
      - "6601:5601"

  # ngserve:
  #   build:
  #     context: .
  #     dockerfile: katpaws-ng/Dockerfile-dev
  #   ports:
  #     - "4300:4200"
  #   volumes:
  #     - ./katpaws-ng/katpaws/src:/ng-app/src
  #     - ./katpaws-ng/katpaws/e2e:/ng-app/e2e
  #   container_name: ngserve_paws

volumes:
  esdata1: